from typing import Any, Dict

from . import Options

# @formatter:off
all_random_settings = {
    "progression_balancing":                            "random",
    "accessibility":                                    "random",
    Options.Goal.internal_name:                         "random",
    Options.DecksToWin.internal_name:                   "random",
    Options.JokerGoal.internal_name:                    "random",
    Options.BeatAnteToWin.internal_name:                "random",
    Options.RequiredStakeForGoal.internal_name:         "random",
    Options.UniqueDeckWins.internal_name:               "random",
    Options.ChallengesForGoal.internal_name:            "random",
    Options.IncludeDecksMode.internal_name:             "random",
    Options.IncludeDecksList.internal_name:             "random",
    Options.IncludeDecksNumber.internal_name:           "random",
    Options.IncludeStakesMode.internal_name:            "random",
    Options.IncludeStakeList.internal_name:             "random",
    Options.IncludeStakesNumber.internal_name:          "random",
    Options.StakeUnlockMode.internal_name:              "random",
    Options.IncludeJokerUnlocks.internal_name:          "random",
    Options.IncludeVoucherUnlocks.internal_name:        "random",
    Options.IncludeAchievements.internal_name:          "random",
    Options.OnlyBossBlindsAreChecks.internal_name:      "random",
    Options.DiscoverJokerAsLocations.internal_name:     "random",
    Options.ExcludeChallenges.internal_name:            "random",
    Options.ChallengeUnlockMode.internal_name:          "random",
    Options.JokerBundles.internal_name:                 "random",
    Options.JokerBundleSize.internal_name:              "random",
    Options.RemoveOrDebuffJokers.internal_name:         "random",
    Options.TarotBundle.internal_name:                  "random",
    Options.CustomTarotBundles.internal_name:           "random",
    Options.PlanetBundle.internal_name:                 "random",
    Options.CustomPlanetBundles.internal_name:          "random",
    Options.SpectralBundle.internal_name:               "random",
    Options.CustomSpectralBundles.internal_name:        "random",
    Options.RemoveOrDebuffConsumables.internal_name:    "random",
    Options.DecksUnlockedFromStart.internal_name:       "random",
    Options.FillerJokers.internal_name:                 "random",
    Options.ArchipelagoConsumableItems.internal_name:   "random",
    Options.OpFillerAmount.internal_name:               "random",
    Options.ShopItems.internal_name:                    "random",
    Options.MinimumShopPrice.internal_name:             "random",
    Options.MaximumShopPrice.internal_name:             "random",
    Options.Traps.internal_name:                        "random",
    Options.ModdedItems.internal_name:                  "random",
    Options.NumberOfImportLicenses.internal_name:       "random",
    Options.ForceYaml.internal_name:                    Options.ForceYaml.option_false,
    Options.DeathLink.internal_name:                    "random",

}

easy_sync_settings = {
    Options.Goal.internal_name:                         Options.Goal.option_beat_decks,
    Options.DecksToWin.internal_name:                   Options.DecksToWin.default,
    Options.JokerGoal.internal_name:                    Options.JokerGoal.default,
    Options.BeatAnteToWin.internal_name:                Options.BeatAnteToWin.default,
    Options.RequiredStakeForGoal.internal_name:         Options.RequiredStakeForGoal.default,
    Options.UniqueDeckWins.internal_name:               Options.UniqueDeckWins.default,
    Options.ChallengesForGoal.internal_name:            Options.ChallengesForGoal.default,
    Options.IncludeDecksMode.internal_name:             Options.IncludeDecksMode.option_number,
    Options.IncludeDecksList.internal_name:             Options.IncludeDecksList.default,
    Options.IncludeDecksNumber.internal_name:           6,
    Options.IncludeStakesMode.internal_name:            Options.IncludeStakesMode.option_choose,
    Options.IncludeStakeList.internal_name:             ["White Stake", "Black Stake", "Purple Stake"],
    Options.IncludeStakesNumber.internal_name:          3,
    Options.StakeUnlockMode.internal_name:              Options.StakeUnlockMode.option_stake_as_item,
    Options.IncludeJokerUnlocks.internal_name:          Options.IncludeJokerUnlocks.option_include_easy,
    Options.IncludeVoucherUnlocks.internal_name:        Options.IncludeVoucherUnlocks.option_include_easy,
    Options.IncludeAchievements.internal_name:          Options.IncludeAchievements.option_include_easy,
    Options.OnlyBossBlindsAreChecks.internal_name:      Options.OnlyBossBlindsAreChecks.option_false,
    Options.DiscoverJokerAsLocations.internal_name:     Options.DiscoverJokerAsLocations.option_none,   # bad for syncs
    Options.ExcludeChallenges.internal_name:            Options.ExcludeChallenges.default,
    Options.ChallengeUnlockMode.internal_name:          Options.ChallengeUnlockMode.option_disabled,
    Options.JokerBundles.internal_name:                 Options.JokerBundles.option_true,   # important for syncs
    Options.JokerBundleSize.internal_name:              Options.JokerBundleSize.default,
    Options.RemoveOrDebuffJokers.internal_name:         Options.RemoveOrDebuffJokers.option_true,
    Options.TarotBundle.internal_name:                  Options.TarotBundle.option_one_bundle,
    Options.CustomTarotBundles.internal_name:           Options.CustomTarotBundles.default,
    Options.PlanetBundle.internal_name:                 Options.PlanetBundle.option_one_bundle,
    Options.CustomPlanetBundles.internal_name:          Options.CustomPlanetBundles.default,
    Options.SpectralBundle.internal_name:               Options.SpectralBundle.option_one_bundle,
    Options.CustomSpectralBundles.internal_name:        Options.CustomSpectralBundles.default,
    Options.RemoveOrDebuffConsumables.internal_name:    Options.RemoveOrDebuffConsumables.default,
    Options.DecksUnlockedFromStart.internal_name:       Options.DecksUnlockedFromStart.default,
    Options.FillerJokers.internal_name:                 Options.FillerJokers.default,
    Options.ArchipelagoConsumableItems.internal_name:   Options.ArchipelagoConsumableItems.default,
    Options.OpFillerAmount.internal_name:               6,
    Options.ShopItems.internal_name:                    10,
    Options.MinimumShopPrice.internal_name:             Options.MinimumShopPrice.default,
    Options.MaximumShopPrice.internal_name:             5,
    Options.Traps.internal_name:                        Options.Traps.option_no_traps,
    Options.ModdedItems.internal_name:                  Options.ModdedItems.default,
    Options.NumberOfImportLicenses.internal_name:       Options.NumberOfImportLicenses.default,
    Options.ForceYaml.internal_name:                    Options.ForceYaml.option_false,
    Options.DeathLink.internal_name:                    Options.DeathLink.default,
}

medium_sync_settings = {
    Options.Goal.internal_name:                         Options.Goal.option_beat_decks,
    Options.DecksToWin.internal_name:                   6,
    Options.JokerGoal.internal_name:                    100,
    Options.BeatAnteToWin.internal_name:                Options.BeatAnteToWin.default,
    Options.RequiredStakeForGoal.internal_name:         "Blue Stake",
    Options.UniqueDeckWins.internal_name:               6,
    Options.ChallengesForGoal.internal_name:            12,
    Options.IncludeDecksMode.internal_name:             Options.IncludeDecksMode.option_number,
    Options.IncludeDecksList.internal_name:             Options.IncludeDecksList.default,
    Options.IncludeDecksNumber.internal_name:           6,
    Options.IncludeStakesMode.internal_name:            Options.IncludeStakesMode.option_choose,
    Options.IncludeStakeList.internal_name:             ["White Stake", "Blue Stake", "Orange Stake"],
    Options.IncludeStakesNumber.internal_name:          3,
    Options.StakeUnlockMode.internal_name:              Options.StakeUnlockMode.option_stake_as_item,
    Options.IncludeJokerUnlocks.internal_name:          Options.IncludeJokerUnlocks.option_include_medium,
    Options.IncludeVoucherUnlocks.internal_name:        Options.IncludeVoucherUnlocks.option_include_medium,
    Options.IncludeAchievements.internal_name:          Options.IncludeAchievements.option_include_medium,
    Options.OnlyBossBlindsAreChecks.internal_name:      Options.OnlyBossBlindsAreChecks.option_false,   # ! for syncs
    Options.DiscoverJokerAsLocations.internal_name:     Options.DiscoverJokerAsLocations.option_none,   # bad for syncs
    Options.ExcludeChallenges.internal_name:            Options.ExcludeChallenges.default,
    Options.ChallengeUnlockMode.internal_name:          Options.ChallengeUnlockMode.option_disabled,
    Options.JokerBundles.internal_name:                 Options.JokerBundles.option_true,   # important for syncs
    Options.JokerBundleSize.internal_name:              5,
    Options.RemoveOrDebuffJokers.internal_name:         Options.RemoveOrDebuffJokers.option_true,
    Options.TarotBundle.internal_name:                  Options.TarotBundle.option_one_bundle,
    Options.CustomTarotBundles.internal_name:           Options.CustomTarotBundles.default,
    Options.PlanetBundle.internal_name:                 Options.PlanetBundle.option_one_bundle,
    Options.CustomPlanetBundles.internal_name:          Options.CustomPlanetBundles.default,
    Options.SpectralBundle.internal_name:               Options.SpectralBundle.option_one_bundle,
    Options.CustomSpectralBundles.internal_name:        Options.CustomSpectralBundles.default,
    Options.RemoveOrDebuffConsumables.internal_name:    Options.RemoveOrDebuffConsumables.default,
    Options.DecksUnlockedFromStart.internal_name:       Options.DecksUnlockedFromStart.default,
    Options.FillerJokers.internal_name:                 Options.FillerJokers.default,
    Options.ArchipelagoConsumableItems.internal_name:   Options.ArchipelagoConsumableItems.default,
    Options.OpFillerAmount.internal_name:               4,
    Options.ShopItems.internal_name:                    10,
    Options.MinimumShopPrice.internal_name:             Options.MinimumShopPrice.default,
    Options.MaximumShopPrice.internal_name:             Options.MaximumShopPrice.default,
    Options.Traps.internal_name:                        Options.Traps.option_medium_amount,
    Options.ModdedItems.internal_name:                  Options.ModdedItems.default,
    Options.NumberOfImportLicenses.internal_name:       Options.NumberOfImportLicenses.default,
    Options.ForceYaml.internal_name:                    Options.ForceYaml.option_false,
    Options.DeathLink.internal_name:                    Options.DeathLink.default,
}

hard_sync_settings = {
    Options.Goal.internal_name:                         Options.Goal.option_beat_decks,
    Options.DecksToWin.internal_name:                   8,
    Options.JokerGoal.internal_name:                    125,
    Options.BeatAnteToWin.internal_name:                13,
    Options.RequiredStakeForGoal.internal_name:         "Purple Stake",
    Options.UniqueDeckWins.internal_name:               8,
    Options.ChallengesForGoal.internal_name:            15,
    Options.IncludeDecksMode.internal_name:             Options.IncludeDecksMode.option_number,
    Options.IncludeDecksList.internal_name:             Options.IncludeDecksList.default,
    Options.IncludeDecksNumber.internal_name:           8,
    Options.IncludeStakesMode.internal_name:            Options.IncludeStakesMode.option_choose,
    Options.IncludeStakeList.internal_name:             ["Red Stake", "Purple Stake", "Gold Stake"],
    Options.IncludeStakesNumber.internal_name:          3,
    Options.StakeUnlockMode.internal_name:              Options.StakeUnlockMode.option_stake_as_item,
    Options.IncludeJokerUnlocks.internal_name:          Options.IncludeJokerUnlocks.option_include_hard,
    Options.IncludeVoucherUnlocks.internal_name:        Options.IncludeVoucherUnlocks.option_include_hard,
    Options.IncludeAchievements.internal_name:          Options.IncludeAchievements.option_include_hard,
    Options.OnlyBossBlindsAreChecks.internal_name:      Options.OnlyBossBlindsAreChecks.option_false,   # ! for syncs
    Options.DiscoverJokerAsLocations.internal_name:     Options.DiscoverJokerAsLocations.option_none,   # bad for syncs
    Options.ExcludeChallenges.internal_name:            Options.ExcludeChallenges.default,
    Options.ChallengeUnlockMode.internal_name:          Options.ChallengeUnlockMode.option_disabled,
    Options.JokerBundles.internal_name:                 Options.JokerBundles.option_true,   # important for syncs
    Options.JokerBundleSize.internal_name:              5,
    Options.RemoveOrDebuffJokers.internal_name:         Options.RemoveOrDebuffJokers.option_true,
    Options.TarotBundle.internal_name:                  Options.TarotBundle.option_one_bundle,
    Options.CustomTarotBundles.internal_name:           Options.CustomTarotBundles.default,
    Options.PlanetBundle.internal_name:                 Options.PlanetBundle.option_one_bundle,
    Options.CustomPlanetBundles.internal_name:          Options.CustomPlanetBundles.default,
    Options.SpectralBundle.internal_name:               Options.SpectralBundle.option_one_bundle,
    Options.CustomSpectralBundles.internal_name:        Options.CustomSpectralBundles.default,
    Options.RemoveOrDebuffConsumables.internal_name:    Options.RemoveOrDebuffConsumables.default,
    Options.DecksUnlockedFromStart.internal_name:       Options.DecksUnlockedFromStart.default,
    Options.FillerJokers.internal_name:                 Options.FillerJokers.default,
    Options.ArchipelagoConsumableItems.internal_name:   Options.ArchipelagoConsumableItems.default,
    Options.OpFillerAmount.internal_name:               2,
    Options.ShopItems.internal_name:                    10,
    Options.MinimumShopPrice.internal_name:             5,
    Options.MaximumShopPrice.internal_name:             20,
    Options.Traps.internal_name:                        Options.Traps.option_high_amount,
    Options.ModdedItems.internal_name:                  Options.ModdedItems.default,
    Options.NumberOfImportLicenses.internal_name:       Options.NumberOfImportLicenses.default,
    Options.ForceYaml.internal_name:                    Options.ForceYaml.option_false,
    Options.DeathLink.internal_name:                    Options.DeathLink.default,
}

extreme_sync_settings = {
    Options.Goal.internal_name:                         Options.Goal.option_beat_decks,
    Options.DecksToWin.internal_name:                   10,
    Options.JokerGoal.internal_name:                    140,
    Options.BeatAnteToWin.internal_name:                14,
    Options.RequiredStakeForGoal.internal_name:         "Purple Stake",
    Options.UniqueDeckWins.internal_name:               10,
    Options.ChallengesForGoal.internal_name:            15,
    Options.IncludeDecksMode.internal_name:             Options.IncludeDecksMode.option_number,
    Options.IncludeDecksList.internal_name:             Options.IncludeDecksList.default,
    Options.IncludeDecksNumber.internal_name:           8,
    Options.IncludeStakesMode.internal_name:            Options.IncludeStakesMode.option_choose,
    Options.IncludeStakeList.internal_name:             ["Green Stake", "Orange Stake", "Gold Stake"],
    Options.IncludeStakesNumber.internal_name:          3,
    Options.StakeUnlockMode.internal_name:              Options.StakeUnlockMode.option_stake_as_item,
    Options.IncludeJokerUnlocks.internal_name:          Options.IncludeJokerUnlocks.option_include_all,
    Options.IncludeVoucherUnlocks.internal_name:        Options.IncludeVoucherUnlocks.option_include_all,
    Options.IncludeAchievements.internal_name:          Options.IncludeAchievements.option_include_all,
    Options.OnlyBossBlindsAreChecks.internal_name:      Options.OnlyBossBlindsAreChecks.option_false,   # ! for syncs
    Options.DiscoverJokerAsLocations.internal_name:     Options.DiscoverJokerAsLocations.option_none,   # bad for syncs
    Options.ExcludeChallenges.internal_name:            Options.ExcludeChallenges.default,
    Options.ChallengeUnlockMode.internal_name:          Options.ChallengeUnlockMode.option_disabled,
    Options.JokerBundles.internal_name:                 Options.JokerBundles.option_true,   # important for syncs
    Options.JokerBundleSize.internal_name:              5,
    Options.RemoveOrDebuffJokers.internal_name:         Options.RemoveOrDebuffJokers.option_false,
    Options.TarotBundle.internal_name:                  Options.TarotBundle.option_individual,
    Options.CustomTarotBundles.internal_name:           Options.CustomTarotBundles.default,
    Options.PlanetBundle.internal_name:                 Options.PlanetBundle.option_individual,
    Options.CustomPlanetBundles.internal_name:          Options.CustomPlanetBundles.default,
    Options.SpectralBundle.internal_name:               Options.SpectralBundle.option_individual,
    Options.CustomSpectralBundles.internal_name:        Options.CustomSpectralBundles.default,
    Options.RemoveOrDebuffConsumables.internal_name:    Options.RemoveOrDebuffConsumables.default,
    Options.DecksUnlockedFromStart.internal_name:       Options.DecksUnlockedFromStart.default,
    Options.FillerJokers.internal_name:                 Options.FillerJokers.default,
    Options.ArchipelagoConsumableItems.internal_name:   Options.ArchipelagoConsumableItems.default,
    Options.OpFillerAmount.internal_name:               0,
    Options.ShopItems.internal_name:                    10,
    Options.MinimumShopPrice.internal_name:             15,
    Options.MaximumShopPrice.internal_name:             30,
    Options.Traps.internal_name:                        Options.Traps.option_mayhem,
    Options.ModdedItems.internal_name:                  Options.ModdedItems.default,
    Options.NumberOfImportLicenses.internal_name:       Options.NumberOfImportLicenses.default,
    Options.ForceYaml.internal_name:                    Options.ForceYaml.option_false,
    Options.DeathLink.internal_name:                    Options.DeathLink.default,
}

easy_async_settings = {
    Options.Goal.internal_name:                         Options.Goal.option_beat_decks,
    Options.DecksToWin.internal_name:                   8,
    Options.JokerGoal.internal_name:                    Options.JokerGoal.default,  # not good goal for asyncs anyway
    Options.BeatAnteToWin.internal_name:                Options.BeatAnteToWin.default,
    Options.RequiredStakeForGoal.internal_name:         Options.RequiredStakeForGoal.default,
    Options.UniqueDeckWins.internal_name:               8,
    Options.ChallengesForGoal.internal_name:            Options.ChallengesForGoal.default,
    Options.IncludeDecksMode.internal_name:             Options.IncludeDecksMode.option_number,
    Options.IncludeDecksList.internal_name:             Options.IncludeDecksList.default,
    Options.IncludeDecksNumber.internal_name:           10,
    Options.IncludeStakesMode.internal_name:            Options.IncludeStakesMode.option_choose,
    Options.IncludeStakeList.internal_name:             ["White Stake", "Green Stake", "Black Stake", "Purple Stake"],
    Options.IncludeStakesNumber.internal_name:          4,
    Options.StakeUnlockMode.internal_name:              Options.StakeUnlockMode.option_stake_as_item_per_deck,
    Options.IncludeJokerUnlocks.internal_name:          Options.IncludeJokerUnlocks.option_include_easy,
    Options.IncludeVoucherUnlocks.internal_name:        Options.IncludeVoucherUnlocks.option_include_easy,
    Options.IncludeAchievements.internal_name:          Options.IncludeAchievements.option_include_easy,
    Options.OnlyBossBlindsAreChecks.internal_name:      Options.OnlyBossBlindsAreChecks.option_true,
    Options.DiscoverJokerAsLocations.internal_name:     Options.DiscoverJokerAsLocations.option_non_legendary,   # bad for syncs
    Options.ExcludeChallenges.internal_name:            Options.ExcludeChallenges.default + ["X-ray Vision", "Double or Nothing", "Bram Poker", "Fragile"],
    Options.ChallengeUnlockMode.internal_name:          Options.ChallengeUnlockMode.default,
    Options.JokerBundles.internal_name:                 Options.JokerBundles.option_false,   # important for syncs
    Options.JokerBundleSize.internal_name:              Options.JokerBundleSize.default,
    Options.RemoveOrDebuffJokers.internal_name:         Options.RemoveOrDebuffJokers.option_true,
    Options.TarotBundle.internal_name:                  Options.TarotBundle.option_individual,
    Options.CustomTarotBundles.internal_name:           Options.CustomTarotBundles.default,
    Options.PlanetBundle.internal_name:                 Options.PlanetBundle.option_individual,
    Options.CustomPlanetBundles.internal_name:          Options.CustomPlanetBundles.default,
    Options.SpectralBundle.internal_name:               Options.SpectralBundle.option_individual,
    Options.CustomSpectralBundles.internal_name:        Options.CustomSpectralBundles.default,
    Options.RemoveOrDebuffConsumables.internal_name:    Options.RemoveOrDebuffConsumables.default,
    Options.DecksUnlockedFromStart.internal_name:       2,
    Options.FillerJokers.internal_name:                 Options.FillerJokers.default,
    Options.ArchipelagoConsumableItems.internal_name:   40,
    Options.OpFillerAmount.internal_name:               7,
    Options.ShopItems.internal_name:                    Options.ShopItems.default,
    Options.MinimumShopPrice.internal_name:             Options.MinimumShopPrice.default,
    Options.MaximumShopPrice.internal_name:             5,
    Options.Traps.internal_name:                        Options.Traps.option_low_amount,
    Options.ModdedItems.internal_name:                  Options.ModdedItems.default,
    Options.NumberOfImportLicenses.internal_name:       Options.NumberOfImportLicenses.default,
    Options.ForceYaml.internal_name:                    Options.ForceYaml.option_false,
    Options.DeathLink.internal_name:                    Options.DeathLink.default,
}

medium_async_settings = {
    Options.Goal.internal_name:                         Options.Goal.option_beat_decks,
    Options.DecksToWin.internal_name:                   10,
    Options.JokerGoal.internal_name:                    100,  # not good goal for asyncs anyway
    Options.BeatAnteToWin.internal_name:                13,
    Options.RequiredStakeForGoal.internal_name:         "Red Stake",
    Options.UniqueDeckWins.internal_name:               10,
    Options.ChallengesForGoal.internal_name:            Options.ChallengesForGoal.default,
    Options.IncludeDecksMode.internal_name:             Options.IncludeDecksMode.option_number,
    Options.IncludeDecksList.internal_name:             Options.IncludeDecksList.default,
    Options.IncludeDecksNumber.internal_name:           10,
    Options.IncludeStakesMode.internal_name:            Options.IncludeStakesMode.option_choose,
    Options.IncludeStakeList.internal_name:             ["White Stake", "Black Stake", "Blue Stake", "Orange Stake"],
    Options.IncludeStakesNumber.internal_name:          4,
    Options.StakeUnlockMode.internal_name:              Options.StakeUnlockMode.option_stake_as_item_per_deck,
    Options.IncludeJokerUnlocks.internal_name:          Options.IncludeJokerUnlocks.option_include_medium,
    Options.IncludeVoucherUnlocks.internal_name:        Options.IncludeVoucherUnlocks.option_include_medium,
    Options.IncludeAchievements.internal_name:          Options.IncludeAchievements.option_include_medium,
    Options.OnlyBossBlindsAreChecks.internal_name:      Options.OnlyBossBlindsAreChecks.option_true,
    Options.DiscoverJokerAsLocations.internal_name:     Options.DiscoverJokerAsLocations.option_non_legendary,   # bad for syncs
    Options.ExcludeChallenges.internal_name:            Options.ExcludeChallenges.default + ["X-ray Vision", "Double or Nothing", "Bram Poker", "Fragile"],
    Options.ChallengeUnlockMode.internal_name:          Options.ChallengeUnlockMode.default,
    Options.JokerBundles.internal_name:                 Options.JokerBundles.option_false,   # important for syncs
    Options.JokerBundleSize.internal_name:              Options.JokerBundleSize.default,
    Options.RemoveOrDebuffJokers.internal_name:         Options.RemoveOrDebuffJokers.option_true,
    Options.TarotBundle.internal_name:                  Options.TarotBundle.option_individual,
    Options.CustomTarotBundles.internal_name:           Options.CustomTarotBundles.default,
    Options.PlanetBundle.internal_name:                 Options.PlanetBundle.option_individual,
    Options.CustomPlanetBundles.internal_name:          Options.CustomPlanetBundles.default,
    Options.SpectralBundle.internal_name:               Options.SpectralBundle.option_individual,
    Options.CustomSpectralBundles.internal_name:        Options.CustomSpectralBundles.default,
    Options.RemoveOrDebuffConsumables.internal_name:    Options.RemoveOrDebuffConsumables.default,
    Options.DecksUnlockedFromStart.internal_name:       2,
    Options.FillerJokers.internal_name:                 Options.FillerJokers.default,
    Options.ArchipelagoConsumableItems.internal_name:   50,
    Options.OpFillerAmount.internal_name:               5,
    Options.ShopItems.internal_name:                    20,
    Options.MinimumShopPrice.internal_name:             Options.MinimumShopPrice.default,
    Options.MaximumShopPrice.internal_name:             Options.MaximumShopPrice.default,
    Options.Traps.internal_name:                        Options.Traps.option_medium_amount,
    Options.ModdedItems.internal_name:                  Options.ModdedItems.default,
    Options.NumberOfImportLicenses.internal_name:       Options.NumberOfImportLicenses.default,
    Options.ForceYaml.internal_name:                    Options.ForceYaml.option_false,
    Options.DeathLink.internal_name:                    Options.DeathLink.default,
}

hard_async_settings = {
    Options.Goal.internal_name:                         Options.Goal.option_beat_decks,
    Options.DecksToWin.internal_name:                   12,
    Options.JokerGoal.internal_name:                    125,  # not good goal for asyncs anyway
    Options.BeatAnteToWin.internal_name:                14,
    Options.RequiredStakeForGoal.internal_name:         "Red Stake",
    Options.UniqueDeckWins.internal_name:               12,
    Options.ChallengesForGoal.internal_name:            14,
    Options.IncludeDecksMode.internal_name:             Options.IncludeDecksMode.option_number,
    Options.IncludeDecksList.internal_name:             Options.IncludeDecksList.default,
    Options.IncludeDecksNumber.internal_name:           12,
    Options.IncludeStakesMode.internal_name:            Options.IncludeStakesMode.option_choose,
    Options.IncludeStakeList.internal_name:             ["Red Stake", "Green Stake", "Blue Stake", "Purple Stake", "Gold Stake"],
    Options.IncludeStakesNumber.internal_name:          5,
    Options.StakeUnlockMode.internal_name:              Options.StakeUnlockMode.option_stake_as_item_per_deck,
    Options.IncludeJokerUnlocks.internal_name:          Options.IncludeJokerUnlocks.option_include_hard,
    Options.IncludeVoucherUnlocks.internal_name:        Options.IncludeVoucherUnlocks.option_include_hard,
    Options.IncludeAchievements.internal_name:          Options.IncludeAchievements.option_include_hard,
    Options.OnlyBossBlindsAreChecks.internal_name:      Options.OnlyBossBlindsAreChecks.option_true,
    Options.DiscoverJokerAsLocations.internal_name:     Options.DiscoverJokerAsLocations.option_all,   # bad for syncs
    Options.ExcludeChallenges.internal_name:            Options.ExcludeChallenges.default + ["Fragile"],
    Options.ChallengeUnlockMode.internal_name:          Options.ChallengeUnlockMode.default,
    Options.JokerBundles.internal_name:                 Options.JokerBundles.option_false,   # important for syncs
    Options.JokerBundleSize.internal_name:              Options.JokerBundleSize.default,
    Options.RemoveOrDebuffJokers.internal_name:         Options.RemoveOrDebuffJokers.option_false,
    Options.TarotBundle.internal_name:                  Options.TarotBundle.option_individual,
    Options.CustomTarotBundles.internal_name:           Options.CustomTarotBundles.default,
    Options.PlanetBundle.internal_name:                 Options.PlanetBundle.option_individual,
    Options.CustomPlanetBundles.internal_name:          Options.CustomPlanetBundles.default,
    Options.SpectralBundle.internal_name:               Options.SpectralBundle.option_individual,
    Options.CustomSpectralBundles.internal_name:        Options.CustomSpectralBundles.default,
    Options.RemoveOrDebuffConsumables.internal_name:    Options.RemoveOrDebuffConsumables.default,
    Options.DecksUnlockedFromStart.internal_name:       2,
    Options.FillerJokers.internal_name:                 Options.FillerJokers.default,
    Options.ArchipelagoConsumableItems.internal_name:   60,
    Options.OpFillerAmount.internal_name:               3,
    Options.ShopItems.internal_name:                    25,
    Options.MinimumShopPrice.internal_name:             5,
    Options.MaximumShopPrice.internal_name:             20,
    Options.Traps.internal_name:                        Options.Traps.option_high_amount,
    Options.ModdedItems.internal_name:                  Options.ModdedItems.default,
    Options.NumberOfImportLicenses.internal_name:       Options.NumberOfImportLicenses.default,
    Options.ForceYaml.internal_name:                    Options.ForceYaml.option_false,
    Options.DeathLink.internal_name:                    Options.DeathLink.default,
}

extreme_async_settings = {
    Options.Goal.internal_name:                         Options.Goal.option_beat_decks,
    Options.DecksToWin.internal_name:                   15,
    Options.JokerGoal.internal_name:                    140,  # not good goal for asyncs anyway
    Options.BeatAnteToWin.internal_name:                15,
    Options.RequiredStakeForGoal.internal_name:         "Gold Stake",
    Options.UniqueDeckWins.internal_name:               12,
    Options.ChallengesForGoal.internal_name:            14,
    Options.IncludeDecksMode.internal_name:             Options.IncludeDecksMode.option_number,
    Options.IncludeDecksList.internal_name:             Options.IncludeDecksList.default,
    Options.IncludeDecksNumber.internal_name:           12,
    Options.IncludeStakesMode.internal_name:            Options.IncludeStakesMode.option_choose,
    Options.IncludeStakeList.internal_name:             ["Red Stake", "Blue Stake", "Purple Stake", "Orange Stake", "Gold Stake"],
    Options.IncludeStakesNumber.internal_name:          5,
    Options.StakeUnlockMode.internal_name:              Options.StakeUnlockMode.option_stake_as_item_per_deck,
    Options.IncludeJokerUnlocks.internal_name:          Options.IncludeJokerUnlocks.option_include_all,
    Options.IncludeVoucherUnlocks.internal_name:        Options.IncludeVoucherUnlocks.option_include_all,
    Options.IncludeAchievements.internal_name:          Options.IncludeAchievements.option_include_all,
    Options.OnlyBossBlindsAreChecks.internal_name:      Options.OnlyBossBlindsAreChecks.option_true,
    Options.DiscoverJokerAsLocations.internal_name:     Options.DiscoverJokerAsLocations.option_all,   # bad for syncs
    Options.ExcludeChallenges.internal_name:            [],
    Options.ChallengeUnlockMode.internal_name:          Options.ChallengeUnlockMode.default,
    Options.JokerBundles.internal_name:                 Options.JokerBundles.option_false,   # important for syncs
    Options.JokerBundleSize.internal_name:              Options.JokerBundleSize.default,
    Options.RemoveOrDebuffJokers.internal_name:         Options.RemoveOrDebuffJokers.option_false,
    Options.TarotBundle.internal_name:                  Options.TarotBundle.option_individual,
    Options.CustomTarotBundles.internal_name:           Options.CustomTarotBundles.default,
    Options.PlanetBundle.internal_name:                 Options.PlanetBundle.option_individual,
    Options.CustomPlanetBundles.internal_name:          Options.CustomPlanetBundles.default,
    Options.SpectralBundle.internal_name:               Options.SpectralBundle.option_individual,
    Options.CustomSpectralBundles.internal_name:        Options.CustomSpectralBundles.default,
    Options.RemoveOrDebuffConsumables.internal_name:    Options.RemoveOrDebuffConsumables.default,
    Options.DecksUnlockedFromStart.internal_name:       2,
    Options.FillerJokers.internal_name:                 Options.FillerJokers.default,
    Options.ArchipelagoConsumableItems.internal_name:   80,
    Options.OpFillerAmount.internal_name:               1,
    Options.ShopItems.internal_name:                    35,
    Options.MinimumShopPrice.internal_name:             10,
    Options.MaximumShopPrice.internal_name:             30,
    Options.Traps.internal_name:                        Options.Traps.option_mayhem,
    Options.ModdedItems.internal_name:                  Options.ModdedItems.default,
    Options.NumberOfImportLicenses.internal_name:       Options.NumberOfImportLicenses.default,
    Options.ForceYaml.internal_name:                    Options.ForceYaml.option_false,
    Options.DeathLink.internal_name:                    Options.DeathLink.default,
}

# @formatter:on


balatro_options_presets: Dict[str, Dict[str, Any]] = {
    "All random": all_random_settings,
    "Easy Sync": easy_sync_settings,
    "Medium Sync": medium_sync_settings,
    "Hard Sync": hard_sync_settings,
    "Extreme Sync": extreme_sync_settings,

    "Easy Async": easy_async_settings,
    "Medium Async": medium_async_settings,
    "Hard Async": hard_async_settings,
    "Extreme Async": extreme_async_settings,

}
